import { GoogleGenerativeAI } from "@google/generative-ai";
import { Resend } from "resend";

import { prisma } from "@/lib/prisma";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY ?? "");
const resend = new Resend(process.env.RESEND_API_KEY ?? "");

export async function generateAndSendWeeklyDigest() {
  const repos = await prisma.repository.findMany({
    where: { backfillStatus: "completed" },
    include: {
      users: { include: { user: true } },
    },
  });

  const now = new Date();
  const sevenDaysAgo = new Date(now);
  sevenDaysAgo.setUTCDate(sevenDaysAgo.getUTCDate() - 7);
  sevenDaysAgo.setUTCHours(0, 0, 0, 0);

  const twoWeeksAgo = new Date(now);
  twoWeeksAgo.setUTCDate(twoWeeksAgo.getUTCDate() - 14);
  twoWeeksAgo.setUTCHours(0, 0, 0, 0);

  for (const repo of repos) {
    const thisWeekMetrics = await prisma.dailyMetric.findMany({
      where: {
        repoId: repo.id,
        date: { gte: sevenDaysAgo },
      },
    });

    const lastWeekMetrics = await prisma.dailyMetric.findMany({
      where: {
        repoId: repo.id,
        date: { gte: twoWeeksAgo, lt: sevenDaysAgo },
      },
    });

    const thisWeek = aggregateMetrics(thisWeekMetrics);
    const lastWeek = aggregateMetrics(lastWeekMetrics);

    const deltas = computeDeltas(thisWeek, lastWeek);
    const significant = Object.entries(deltas).filter(
      ([, change]) => Math.abs(change) > 15
    );

    if (significant.length === 0) continue;

    const narrative = await generateNarrative(repo.fullName, deltas, thisWeek);

    const emails = repo.users
      .map((ur) => ur.user.email)
      .filter((e): e is string => !!e);

    if (emails.length === 0) continue;

    const html = `
      <h1>DevPulse Weekly: ${repo.fullName}</h1>
      <div style="font-family: system-ui; line-height: 1.6; color: #1a1a1a;">
        ${narrative.split("\n\n").map((p) => `<p>${p}</p>`).join("")}
      </div>
      <p style="color: #666; font-size: 12px; margin-top: 24px;">
        Generated by DevPulse. Unsubscribe by disconnecting this repository.
      </p>
    `;

    await sendWeeklyDigest(emails, `DevPulse Weekly: ${repo.fullName}`, html);
  }
}

async function sendWeeklyDigest(
  emails: string[],
  subject: string,
  html: string
) {
  const from = process.env.DIGEST_FROM_EMAIL ?? "digest@devpulse.app";

  for (const email of emails) {
    try {
      await resend.emails.send({
        from,
        to: email,
        subject,
        html,
      });
    } catch (error) {
      console.error(`Failed to send digest to ${email}:`, error);
    }
  }
}

interface AggregatedMetrics {
  prsMerged: number;
  avgCycleTime: number;
  deploymentsTotal: number;
  deploymentFailures: number;
  reviewsSubmitted: number;
  avgTimeToFirstReview: number;
}

function aggregateMetrics(
  metrics: {
    prsMerged: number;
    avgCycleTimeSeconds: number;
    deploymentsTotal: number;
    deploymentFailures: number;
    reviewsSubmitted: number;
    avgTimeToFirstReviewSeconds: number;
  }[]
): AggregatedMetrics {
  if (metrics.length === 0) {
    return {
      prsMerged: 0,
      avgCycleTime: 0,
      deploymentsTotal: 0,
      deploymentFailures: 0,
      reviewsSubmitted: 0,
      avgTimeToFirstReview: 0,
    };
  }

  const totalPrsMerged = metrics.reduce((s, m) => s + m.prsMerged, 0);
  const totalCycle = metrics.reduce(
    (s, m) => s + m.avgCycleTimeSeconds * m.prsMerged,
    0
  );

  return {
    prsMerged: totalPrsMerged,
    avgCycleTime: totalPrsMerged > 0 ? totalCycle / totalPrsMerged : 0,
    deploymentsTotal: metrics.reduce((s, m) => s + m.deploymentsTotal, 0),
    deploymentFailures: metrics.reduce((s, m) => s + m.deploymentFailures, 0),
    reviewsSubmitted: metrics.reduce((s, m) => s + m.reviewsSubmitted, 0),
    avgTimeToFirstReview:
      metrics.length > 0
        ? metrics.reduce((s, m) => s + m.avgTimeToFirstReviewSeconds, 0) /
          metrics.length
        : 0,
  };
}

function computeDeltas(
  current: AggregatedMetrics,
  previous: AggregatedMetrics
): Record<string, number> {
  const pctChange = (curr: number, prev: number) =>
    prev > 0 ? ((curr - prev) / prev) * 100 : curr > 0 ? 100 : 0;

  return {
    prsMerged: pctChange(current.prsMerged, previous.prsMerged),
    avgCycleTime: pctChange(current.avgCycleTime, previous.avgCycleTime),
    deploymentsTotal: pctChange(
      current.deploymentsTotal,
      previous.deploymentsTotal
    ),
    deploymentFailures: pctChange(
      current.deploymentFailures,
      previous.deploymentFailures
    ),
    reviewsSubmitted: pctChange(
      current.reviewsSubmitted,
      previous.reviewsSubmitted
    ),
    avgTimeToFirstReview: pctChange(
      current.avgTimeToFirstReview,
      previous.avgTimeToFirstReview
    ),
  };
}

async function generateNarrative(
  repoName: string,
  deltas: Record<string, number>,
  metrics: AggregatedMetrics
): Promise<string> {
  if (!process.env.GEMINI_API_KEY) {
    return "Weekly digest generation is not configured (GEMINI_API_KEY not set).";
  }

  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

  const prompt = `You are an engineering coach. Given these metric changes for the repository "${repoName}" over the past week, write a 3-paragraph plain-English summary.

Metric changes (percentage change from last week):
${Object.entries(deltas)
  .filter(([, v]) => Math.abs(v) > 15)
  .map(([k, v]) => `- ${k}: ${v > 0 ? "+" : ""}${Math.round(v)}%`)
  .join("\n")}

Current week totals:
- PRs merged: ${metrics.prsMerged}
- Avg cycle time: ${Math.round(metrics.avgCycleTime / 3600)} hours
- Total deployments: ${metrics.deploymentsTotal}
- Deployment failures: ${metrics.deploymentFailures}
- Reviews submitted: ${metrics.reviewsSubmitted}

First paragraph: what improved. Second paragraph: what regressed or needs attention. Third paragraph: one specific recommendation. Be concrete, not generic. Do not mention percentages or raw numbers — translate them into meaning.`;

  const result = await model.generateContent(prompt);
  return result.response.text();
}
